src/client/multipart.rs

sync upstream: https://github.com/seanmonstar/reqwest/pull/2525

feat(multipart): Expose a Form::into_stream() method on async multipart forms

---

src/client/http.rs
src/mimic/macros.rs
src/mimic/mod.rs
tests/brotli.rs
tests/client.rs
tests/deflate.rs
tests/gzip.rs
tests/zstd.rs

Some users may not need it, it will be up to the user to decide
- https://github.com/seanmonstar/reqwest/issues/1073
- https://github.com/seanmonstar/reqwest/issues/2279

feat: remove internal headers cache

---

.github/compilation-guide/build.yml
README.md

Update Supported Platforms in README.md and GitHub Actions workflow.
**Supported Platforms:**
- **Linux:** amd64, aarch64, armv7
- **muslLinux:** amd64, aarch64
- **Windows:** amd64
- **macOS:** amd64, aarch64

build: Update compilation guide

---

src/cookie.rs

This pull request introduces a new method for clearing cookies in the `CookieStore` trait and its implementation for the `Jar` struct in the `src/cookie.rs` file. The most important changes include:
Enhancements to `CookieStore` trait:
* Added `clear` method to the `CookieStore` trait to allow removal of all cookies from the store.
Implementation in `Jar` struct:
* Implemented the `clear` method in the `Jar` struct to clear all cookies by writing to the internal storage.

feat(cookie): Add optional clear method to `CookieStore` implementation

---

tests/proxy.rs

merge: https://github.com/0x676e67/rquest/pull/442

tests: serialize tests that read/write the same environment variable

---

Cargo.toml
tests/badssl.rs

close: https://github.com/0x676e67/rquest/issues/462

fix(deps): Fix alps use new endpoint negotiation

---

Cargo.toml

from: https://github.com/0x676e67/rquest/pull/467

build(deps): update boring requirement from 4.15.7 to 4.15.8

---

src/proxy.rs

from upstream: https://github.com/seanmonstar/reqwest/pull/2559

fix(proxy): Fix `no_proxy` on Windows

---

Cargo.toml
README.md
src/util/client/network.rs

close: https://github.com/0x676e67/rquest/issues/481

style(network): fmt code

---

src/connect.rs
src/proxy.rs
src/util/client/dst.rs
src/util/client/mod.rs
src/util/client/request.rs

This pull request includes several changes to improve the handling of HTTP headers and the structure of the `Dst` and `InnerRequest` components. The most important changes include the introduction of `Arc` for headers, refactoring of user-agent handling, and the addition of the `Dst` struct.
* [`src/connect.rs`](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dde381bee13daec97b9L670-R671): Changed `headers` to use `Arc<HeaderMap>` and refactored user-agent handling by introducing `add_user_agent` and `add_user_agent_if_missing` functions. [[1]](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dde381bee13daec97b9L670-R671) [[2]](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dde381bee13daec97b9L693-R695) …

refactor internal request design

---

src/client/http.rs
src/client/request.rs

close: https://github.com/0x676e67/rquest/issues/310

feat(request): Allow request level setting of header ordering

---

src/client/decoder.rs

close: https://github.com/0x676e67/rquest/issues/506

fix(decoder): fix conditional compilation of decompress features

---

Cargo.toml
examples/emulation_provider.rs
src/tls/config.rs
src/tls/conn/boring.rs
src/tls/conn/mod.rs
src/tls/ext.rs
tests/badssl.rs

from: https://github.com/0x676e67/boring2/pull/57
close: https://github.com/0x676e67/rquest/issues/514

feat(tls): allow overriding AES encryption for TLS ECH

---

.github/workflows/ci.yml
Cargo.toml
src/client/decoder.rs
tests/zstd.rs

close: https://github.com/0x676e67/rquest/issues/516

fix(decoder): Handle multi-frame zstd response body decompression

---

src/cookie.rs

This pull request includes changes to the `src/cookie.rs` file to standardize the usage of the `RawCookie` type from the `cookie_crate` library. The most important changes include replacing the `cookie_crate::Cookie` type with `RawCookie` and adding a method to retrieve the inner `RawCookie` instance.
Standardization of `RawCookie` type:
* Replaced `cookie_crate::Cookie` with `RawCookie` in the `pub use` statement.
* Updated the `Cookie` struct to use `RawCookie` instead of `cookie_crate::Cookie`.
* Modified methods to use `RawCookie::parse` and `RawCookie::new` instead of `cookie_crate::Cookie::parse` and `cookie_crate::Cookie::new`. [[1]](diffhunk://#diff-644c16269b9bbce8fca31aa700b38bc538bbe6045cca8644e24e52fb47b28a75L62-R62) [[2]](diffhunk://#diff-644c16269b9bbce8fca31aa700b38bc538bbe6 …

feat(cookie): Impl `into_inner` for `Cookie`

---

Cargo.toml
src/client/http.rs
src/client/request.rs
src/client/websocket/mod.rs
src/lib.rs
src/tls/conn/boring.rs
src/util/client/connect/http.rs
src/util/client/dst.rs
src/util/client/network.rs

close: https://github.com/0x676e67/rquest/issues/591

feat(client): ClientBuilder::interface on `solaris`/`illumos`

---

src/client/config/http1.rs
src/client/config/http2.rs
src/client/http.rs
src/tls/config.rs

refactor(config): Remove public config fields and improve backward compatibility

---

src/client/http.rs

close: https://github.com/0x676e67/rquest/issues/313

feat(client): Add identity to be used for client certificate authentication

---

src/redirect.rs
tests/redirect.rs

sync: https://github.com/seanmonstar/reqwest/pull/2664

fix(redirect): make the number of redirects of policy matches its maximum limit

---

src/client/client.rs
src/client/request.rs
src/client/websocket/mod.rs
src/config.rs
src/connect.rs
src/core/client/conn/http1.rs
src/core/client/request.rs
src/core/ext/mod.rs
src/dns/resolve.rs
src/lib.rs

sync upstream: https://github.com/seanmonstar/reqwest/commit/c81ccb24aa8e9975808ca9dce6a4e0f96a077ff9

refactor: Store request timeout in request extensions instead

---

src/core/client/proxy/matcher.rs

from: https://github.com/seanmonstar/reqwest/issues/2715

fix(proxy): set https system proxy on windows

---

Cargo.toml
examples/request_with_proxy.rs
src/client/client/mod.rs
src/connect.rs
src/core/client/connect/proxy/mod.rs
src/core/client/connect/proxy/socks/mod.rs
src/core/client/connect/proxy/socks/v4/mod.rs
src/core/client/connect/proxy/socks/v5/mod.rs
src/dns/resolve.rs

close: https://github.com/0x676e67/wreq/issues/682

refactor(socks): Reuse socks module logic from hyper-util

---

src/client/client/mod.rs
src/connect.rs

close: https://github.com/0x676e67/wreq/issues/760

feat(client): Add `TCP_REUSEADDR` support for client sockets

---

src/client/http/connect/connector.rs
src/client/http/mod.rs
src/client/http/service.rs
src/client/http/types.rs
src/client/layer/redirect/mod.rs
src/core/client/mod.rs
src/core/client/service/mod.rs

close: https://github.com/0x676e67/wreq/issues/927

fix(client): ensure Accept-Encoding header is applied correctly

---

src/error.rs
tests/client.rs
tests/layers.rs
tests/redirect.rs
tests/zstd.rs

fix: https://github.com/0x676e67/rnet/issues/348

fix(error): drop leftover debug logging
