0x676e67/wreq

examples/impersonate_settings.rs
src/client/http.rs
src/http2.rs

- Added an implementation of the IntoStreamDependency trait for a tuple of (u32, u8, bool).
This allows a tuple containing a stream ID, weight, and exclusive flag to be converted into a StreamDependency.
- Added an implementation of the IntoStreamDependency trait for StreamDependency itself.
This allows a StreamDependency to be converted into itself, which is useful for generic conversions.

feat: Implement `IntoStreamDependency` for tuple and `StreamDependency`

---

examples/impersonate_builder.rs
src/imp/mod.rs

- Added detailed documentation for the `impersonate` method, including arguments and return value.
- Added detailed documentation for the `impersonate_os` method, including arguments and return value.
- Added detailed documentation for the `skip_http2` method, including arguments and return value.
- Added detailed documentation for the `skip_headers` method, including arguments and return value.
- Improved overall clarity and completeness of the method documentation.

docs: Enhance documentation for `ImpersonateBuilder` methods

---

Cargo.toml
examples/websocket.rs
src/client/websocket/mod.rs
src/error.rs

- Improved error handling for missing `Sec-Websocket-Accept` header and protocol mismatches.
- Renamed `with_builder` to `configure_request` for better clarity.
- Simplified the check for empty protocols using `map_or`.
- Changed some API signatures for better usability and consistency.
- Enhanced overall code readability and maintainability.

refactor(websocket): Improve error handling, rename APIs, and update API signatures

---

Cargo.toml
examples/base_url.rs
examples/http2_websocket.rs
examples/impersonate_builder.rs
examples/impersonate_psk.rs
examples/impersonate_settings.rs
examples/request_with_cookie_store.rs
examples/request_with_interface.rs
examples/request_with_local_address.rs
examples/request_with_proxy.rs
examples/request_with_redirect.rs
examples/request_with_version.rs
examples/set_proxies.rs
examples/set_redirect.rs
examples/set_root_cert_store.rs
examples/websocket.rs
src/client/http.rs
src/client/request.rs
src/client/websocket/mod.rs
src/error.rs
src/util/client/mod.rs
src/util/client/request.rs

close: https://github.com/0x676e67/rquest/issues/369

feat: Add `HTTP/2` support for `WebSocket`

---

Cargo.toml
examples/http2_websocket.rs
examples/websocket.rs
src/client/websocket/json.rs
src/client/websocket/message.rs
src/client/websocket/mod.rs
src/error.rs
src/lib.rs

refactor: Replace async-tungstenite with lighter tokio-tungstenite implementation
- Replaced `async-tungstenite` dependency with `tokio-tungstenite` for a lighter implementation.
- Updated Cargo.toml to reflect the new dependency.
- Adjusted WebSocket-related code to work with `tokio-tungstenite`.
- Improved overall performance and reduced dependency bloat.

refactor(websocket): Replace `async-tungstenite` with lighter `tokio-tungstenite` implementation

---

src/client/http.rs
src/imp/chrome.rs
src/imp/firefox.rs
src/imp/macros.rs
src/imp/mod.rs
src/imp/okhttp.rs
src/imp/safari.rs

This pull request includes several changes to improve the consistency and functionality of the HTTP context configuration across different browser impersonations. The most significant changes involve refactoring function names and parameters to enhance clarity and maintainability.
Refactoring for improved clarity and consistency:
* `src/imp/chrome.rs`, `src/imp/firefox.rs`, `src/imp/okhttp.rs`, `src/imp/safari.rs`: Renamed the function `http_config` to `http_context` and updated the function parameters to use `ImpersonateOption` instead of individual parameters for `skip_http2` and `skip_headers`. [[1]](diffhunk://#diff-d3a45118246025f394197b05c790e52fe4eaa04b165f71aa92220d4d6a41cfc5L17-R24) [[2]](diffhunk://#diff-d3a45118246025f394197b05c790e52fe4eaa04b165f71aa92220d4d6a41cfc5L35-R36) …

chore: fmt imports

---

Cargo.toml

This pull request includes a change to the `Cargo.toml` file to update the dependencies for the project. The most important change involves modifying the `tokio` dependency to streamline its features.
Dependency updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L103-R103): Modified the `tokio` dependency to remove the `rt` feature, keeping only `net` and `time` features.

deps(tokio): Remove unused `rt` feature

---

Cargo.toml

This pull request includes updates to dependencies in the `Cargo.toml` file. The most important changes include modifying the features of the `tokio` dependency and updating the version of the `ipnet` dependency.
Dependency updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L103-R105): Modified the `tokio` dependency to remove the `rt` feature and condense the feature list into a single line.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L103-R105): Updated the `ipnet` dependency from version `2.10.0` to `2.11.0`.

deps(ipnet): bump version to v2.11.0

---

src/client/http.rs

This pull request focuses on refactoring the `ClientBuilder` and `Config` structures in the `src/client/http.rs` file to improve the handling of TLS configurations and headers. The most important changes include the introduction of a `TlsConfig` structure, removal of the `HttpContext` structure, and updates to various methods to reflect these changes.
Refactoring and improvements:
* Replaced `HttpContext` with `TlsConfig` in `Config` struct and `ClientBuilder` methods. [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L124-R126) [[2]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L167-R176) [[3]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L196-R200)
* Added `headers` and …

feat(client): Apply configuration sequentially

---

examples/request_with_version.rs
src/util/client/mod.rs
tests/client.rs

This pull request includes changes to improve HTTP version handling and testing in the `rquest` library. The most important changes include modifying the request version handling, adding new tests for HTTP versions, and removing outdated tests.
Improvements to HTTP version handling:
* [`examples/request_with_version.rs`](diffhunk://#diff-619e2fef0362bd5ed01b80b7abf650e69b24e30d46c69646fd4bebee4fdfe3aeL22-R22): Replaced `println!("{:?}", resp.version());` with `assert_eq!(resp.version(), Version::HTTP_11);` to ensure the response version is HTTP/1.1.
* [`src/util/client/mod.rs`](diffhunk://#diff-df53afa88f56f61a1ced749063f0cadd3e28f953e2fe205b1724790292ac945dL180-L205): Added `is_h2` method to check if the ALPN protocol is HTTP/2, and updated the `request` method to handle ALPN protocols …

fix: Ensure HTTP version negotiation for non-TLS requests

---

Cargo.toml
src/tls/cert/mod.rs
src/tls/conn/layer.rs
src/tls/ext.rs
src/tls/mod.rs

This pull request includes several updates and refactorings to the `Cargo.toml` and `src/tls` files. The main changes involve updating dependencies and refactoring the code to remove unsafe blocks and improve readability.
Dependency Updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L112-R114): Updated the `boring2`, `boring-sys2`, and `tokio-boring2` dependencies from version `4.15.0` to `4.15.1`.
Code Refactoring:
* [`src/tls/ext.rs`](diffhunk://#diff-8ea4f8c12a8a50293cee375c2af8cf7aa873af6e6dc534da267b2904b7237836L4-R4): Added `SslOptions` to the import statement from `boring2::ssl`.
* [`src/tls/ext.rs`](diffhunk://#diff-8ea4f8c12a8a50293cee375c2af8cf7aa873af6e6dc534da267b2904b7237836L120-R123): Refactored the `enable_ech_grease` …

refactor: Replace unsafe methods with safe methods in `ConnectConfiguration`

---

src/client/http.rs
src/connect.rs

This pull request includes several changes to the `src/connect.rs` and `src/client/http.rs` files to simplify the `ConnectorBuilder` and `ConnectorService` classes, remove redundant code, and improve the overall structure. The most important changes are:
Improvements to `ConnectorBuilder` and `ConnectorService`:
* Simplified the `ConnectorBuilder` by converting setter methods (`set_timeout`, `set_keepalive`, `set_verbose`) to builder pattern methods (`timeout`, `keepalive`, `verbose`). [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L258-R262) [[2]](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dde381bee13daec97b9L126-R150)
* Removed the `InnerTLS` enum and replaced it with direct usage of `BoringTlsConnector`, eliminating unnecessary …

perf(connector): Optimize performance of switching TLS connector

---

src/client/http.rs
src/util/client/mod.rs

This pull request includes changes to improve the naming consistency for HTTP/2 timer methods and documentation in the `src/client/http.rs` and `src/util/client/mod.rs` files. The most important changes include renaming the timer method and updating related documentation references.
Improvements to naming consistency:
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L227-R227): Renamed the `timer` method to `http2_timer` to reflect its purpose more clearly.
* [`src/util/client/mod.rs`](diffhunk://#diff-df53afa88f56f61a1ced749063f0cadd3e28f953e2fe205b1724790292ac945dL1169-R1175): Updated the method name from `timer` to `http2_timer` and modified the associated documentation to use `http2` instead of `h2`, ensuring consistency with …

chore(client): rename client builder http2 timer name from `timer` to `http2_timer`

---

src/client/http.rs
src/connect.rs

Change the initialization of `connector_layers` to lazy initialization when used to avoid initialization when not necessary, thereby optimizing performance.
- Modify the `connector_layer` method of `ClientBuilder` so that it initializes `connector_layers` only when it is called for the first time.
- In this way, unnecessary memory allocation and initialization operations are reduced, improving performance.

perf(connect): Delay connector layer initialization to improve performance

---

src/client/http.rs

This pull request includes a minor documentation update to the `Client` implementation in the `src/client/http.rs` file. The change adds a note about the connection pool sharing behavior when cloning a `Client` instance.
Documentation update:
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90R1505): Added a note to the `Client` documentation indicating that the cloned client will share the connection pool with the original `Client`.

docs(client): Update client `cloned` method documentation

---

src/client/http.rs

This pull request focuses on refactoring the error handling in the `src/client/http.rs` file by consolidating the error types used throughout the code. The changes primarily involve replacing `crate::Error` with `Error` to streamline error management.
Key changes include:
Error handling refactor:
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L21-R21): Updated various `use` statements to include `Error` from `crate::error` and removed redundant imports. [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L21-R21) [[2]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L31-R31)
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a5 …

chore: Simplified error qualifier types

---

Cargo.toml
src/proxy.rs

This pull request introduces several changes to add support for macOS system configuration as an optional feature. The most important changes include modifications to the `Cargo.toml` file to define the new feature and updates to the `src/proxy.rs` file to conditionally compile code based on the feature flag.
* Added `macos-system-configuration` to the default features list.
* Defined the `macos-system-configuration` feature to use the `system-configuration` dependency.
* Marked the `system-configuration` dependency as optional for macOS targets.
* Updated the import statement for `system_configuration` to be conditional on the `macos-system-configuration` feature.
* Modified the `parse_setting_from_dynamic_store` and `get_from_platform_impl` functions to conditionally compile based on …

build(deps): macOS platform dependencies are minimized as much as possible

---

Cargo.toml
examples/client_chain.rs
src/lib.rs
src/proxy.rs
src/util/client/connect/http.rs

This pull request introduces a new feature for supporting Apple platform's network device binding and includes several related changes across multiple files. The most important changes are listed below:
* Added `apple-bindable-device` dependency to `Cargo.toml` to enable the new feature for Apple platforms.
* Made the `libc` dependency optional for Apple platforms in `Cargo.toml`.
* Updated the `required-features` for the `client_chain` example to include the new `apple-bindable-device` feature in `Cargo.toml`.
* Changed the network interface from `"utun4"` to `"utun6"` in the `client_chain.rs` example to reflect the new feature.
* Updated the `cfg_bindable_device` and `cfg_non_bindable_device` macros in `src/lib.rs` to conditionally include the new feature for Apple platforms. …

build(deps): Apple platform dependencies are minimized as much as possible

---

Cargo.toml
src/client/http.rs
src/client/request.rs
src/lib.rs
src/tls/conn/mod.rs
src/util/client/connect/http.rs
src/util/client/mod.rs
src/util/client/network.rs

This pull request includes significant changes to how the code handles conditional compilation for bindable devices. The primary focus is on replacing the `cfg_bindable_device` and `cfg_non_bindable_device` macros with direct `#[cfg]` attributes. Additionally, there are some minor formatting adjustments in the `Cargo.toml` file.
* Removed `cfg_bindable_device` and `cfg_non_bindable_device` macros and replaced them with direct `#[cfg]` attributes in various files. [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L31-R31) [[2]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L856) [[3]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90R866-L874) …

build: Visualize macro conditional compilation

---

Cargo.toml
src/connect.rs
src/proxy.rs

This pull request includes several updates to the `Cargo.toml` file and enhancements to the SOCKS proxy support in the `src/connect.rs` and `src/proxy.rs` files. The most important changes include the addition of new dependencies, the introduction of `remote_dns` support for SOCKS4 proxies, and the refactoring of related code to accommodate these enhancements.
* Updated `ProxyScheme::Socks4` to include a `remote_dns` boolean field.
* Introduced the `socks4a` variant in `ProxyScheme` to support DNS resolution via the proxy.
* Updated the `connect_socks` method in `ConnectorService` to handle the `remote_dns` field for SOCKS4 proxies.
* Modified the `socks` module to accommodate the `remote_dns` field in `ProxyScheme::Socks4`.
* Updated the `fmt::Debug` implementation for `ProxyScheme` to …

feat(proxy): Add `socks4a` proxy protocol support

---

src/client/websocket/mod.rs
src/error.rs

This pull request includes several changes to the `src/client/websocket/mod.rs` and `src/error.rs` files to simplify error handling and improve code readability. The most important changes include consolidating error imports, refactoring error creation, and modifying error handling in the `WebSocketResponse` and `WebSocket` implementations.
Improvements to error handling and code readability:
* [`src/client/websocket/mod.rs`](diffhunk://#diff-9c330e1b4c96db3a94063fa8051a4e5c011658571686e814f740892635a92f6fL14-R22): Consolidated imports from `crate::error` and moved `pub use message::{CloseCode, CloseFrame, Message, Utf8Bytes};` to the top of the file.
* [`src/client/websocket/mod.rs`](diffhunk://#diff-9c330e1b4c96db3a94063fa8051a4e5c011658571686e814f740892635a92f6fL222-R222): Refactored …

chore(websocket): Simplify error handling and improve code readability

---

Cargo.toml

This pull request includes a small but important change to the `Cargo.toml` file to ensure compatibility with additional runtime features.
Dependency update:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L109-R109): Updated the `tokio` dependency to include the `rt` feature in addition to `net` and `time` to enable runtime features.

Revert "deps(tokio): Remove unused `rt` feature" 

---

src/connect.rs

This pull request includes several changes to the `src/connect.rs` file aimed at improving logging and DNS resolution. The most important changes are:
Logging improvement:
* [`src/connect.rs`](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dde381bee13daec97b9L322-R322): Modified the logging statement in the `ConnectorService` implementation to log the URI of the destination instead of the destination itself.
DNS resolution improvement:
* [`src/connect.rs`](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dde381bee13daec97b9L766-R765): Replaced the use of the `ToSocketAddrs` trait with `tokio::net::lookup_host` for asynchronous DNS resolution in the `socks` module.
Code cleanup:
* [`src/connect.rs`](diffhunk://#diff-4e7bfdc1a4370e34beb83e080ba29965735d732b714e5dd …

perf(socks): Use non-blocking DNS query in Socks connection process

---

src/connect.rs
src/tls/conn/boring.rs
src/tls/conn/mod.rs
src/tls/mod.rs
src/util/client/mod.rs

This pull request includes significant changes to the `HttpsConnector` and related TLS components to simplify and enhance the codebase. The most important changes include the introduction of the `BoringTlsConnector`, the renaming and restructuring of files, and the modification of methods to use the new connector. These changes improve the maintainability and functionality of the TLS connection setup.
* [`src/tls/conn/boring.rs`](diffhunk://#diff-d98b0d1de580025b82e10754916d11d3d7b8817ca234aa0768743acd80cb7536L3-L27): Introduced `BoringTlsConnector` to replace `HttpsLayer` and added methods to configure TLS settings. [[1]](diffhunk://#diff-d98b0d1de580025b82e10754916d11d3d7b8817ca234aa0768743acd80cb7536L3-L27) [[2]](diffhunk://#diff-d98b0d1de580025b82e10754916d11d3d7b8817ca234aa0768743acd8 …

refactor(tls): Refactor TLS connector structure

---

src/client/http.rs
src/tls/cert/store.rs
src/tls/conf.rs

This pull request includes several changes to improve the debugging capabilities and simplify the codebase in the `src/client/http.rs` and `src/tls` modules. The most important changes include adding new fields to the `Config` struct, implementing the `Debug` trait for several structs, and removing the `impl_debug` macro usage.
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L1542-R1552): Added the `Debug` trait to the `ClientInner` and `Proxies` structs. [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L1542-R1552) [[2]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L1607-L1622)
* [`src/tls/cert/store.rs`](diffhunk://#diff-865db2a8a6febb7baa5806b7175e17ee81ea2 …

chore: Improve Debug implementation

---

Cargo.toml

This pull request includes a version update to the `Cargo.toml` file to ensure dependencies are up to date.
Dependency updates:
* Updated `boring2` from version `4.15.2` to `4.15.3` to include the latest features and fixes.
* Updated `tokio-boring2` from version `4.15.2` to `4.15.3` to stay consistent with `boring2` and benefit from the latest improvements.

build(deps): update boring requirement from 4.15.2 to 4.15.3

---

examples/base_url.rs
examples/headers_order.rs
examples/set_cookie_provider.rs
examples/set_cookies.rs
src/util/client/request.rs

Tracing line: https://github.com/hyperium/hyper/blob/621d8e4d7788bfd2d62d15d40a73efae7f9a0bf0/src/proto/h2/client.rs#L664
This pull request includes several changes to the `examples/headers_order.rs` and `src/util/client/request.rs` files to improve the handling of HTTP requests and headers. The most important changes include modifying the request method in the example, updating the `add_content_length_header` function to consider the HTTP method, and introducing a new utility function to check method payload semantics.
Improvements to HTTP request handling:
* [`examples/headers_order.rs`](diffhunk://#diff-72316ed9846e39411e1a7fca2d37c43914ff6e88acf89c21aeb47fa4b1bb51efL32-R32): Changed the request method from `POST` to `GET` in the example to demonstrate a different type of request. …

fix: Ignore Content-Length for methods without payload semantics

---

src/tls/mod.rs
src/util/client/mod.rs
tests/client.rs

This pull request introduces changes to the `src/util/client/mod.rs` file to include the HTTP version in the `PoolKey` struct and updates the related methods accordingly. Additionally, a new test has been added to verify the behavior of the client pool cache.
Changes to `src/util/client/mod.rs`:
* Added `version` field to `PoolKey` struct and updated the `new` method to include the `version` parameter.
* Updated the `Dst::new` method to accept the `version` parameter and pass it to `PoolKey::new`.
* Modified the `Dst::new` method to pass the `version` parameter to `PoolKey::new` when constructing a `Dst` instance.
* Updated the `request` method to extract the HTTP version from the request and pass it to the `Dst::new` method.
* Modified the `request` method to include the `version` …

feat(pool): Connection pool distinguishes request versions

---

Cargo.toml

This pull request includes a version bump for the `boring2` and `tokio-boring2` dependencies in the `Cargo.toml` file. The changes update these dependencies from version `4.15.3` to `4.15.5`.
Dependency updates:
* Updated `boring2` dependency from version `4.15.3` to `4.15.5` in `Cargo.toml`
* Updated `tokio-boring2` dependency from version `4.15.3` to `4.15.5` in `Cargo.toml`

build(deps): update boring requirement from 4.15.3 to 4.15.5

---

Cargo.toml

fix: https://github.com/0x676e67/rquest/issues/438
This may or may not be fixed, no one wants to maintain these

build(deps): update boring requirement from 4.14.0 to 4.15.6

---

src/imp/chrome.rs
src/imp/mod.rs
src/tls/conn/layer.rs
src/tls/conn/mod.rs
src/tls/ext.rs
src/tls/mod.rs

This pull request includes several changes to the TLS settings and introduces a new Chrome version (v133) with specific configurations. The most important changes are grouped by theme below:
* Added a new field `alps_use_new_codepoint` to the `ChromeTlsSettings` and `HttpsLayerSettings` structs to support the new ALPS codepoint. [[1]](diffhunk://#diff-d3a45118246025f394197b05c790e52fe4eaa04b165f71aa92220d4d6a41cfc5R267-R269) [[2]](diffhunk://#diff-83bb6cf4e4ce2ec69ffa0070af651d1ce24bb424f8ed3a13abc2c052dc021cadR91)
* Updated the `alps_protos` method in `ConnectConfigurationExt` to accept the new ALPS codepoint parameter. [[1]](diffhunk://#diff-8ea4f8c12a8a50293cee375c2af8cf7aa873af6e6dc534da267b2904b7237836L50-R54) [[2]](diffhunk://#diff-8ea4f8c12a8a50293cee375c2af8cf7aa873af6e6dc534da267b …

feat: Add chrome133 support

---

README.md
src/imp/firefox.rs
src/imp/mod.rs

This pull request includes updates to the `README.md` file and enhancements to the Firefox TLS settings in the `src/imp/firefox.rs` file. The most important changes include adding a new Firefox version (135) support, updating the TLS settings macro, and enhancing the documentation.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L10-R12): Added a disclaimer about the project's intended use for personal learning purposes only and updated the list of supported browser versions with corrected punctuation. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L10-R12) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L101-R119)
Enhancements to Firefox …

feat: Add Firefox135 support

---

README.md
src/imp/firefox.rs
src/imp/mod.rs

Firefox135 has many settings. When in privacy mode, the psk_key_exchange_modes extension will be disabled, and PSK will also be disabled.
This is only available in non-private mode emulation

feat: Add Android Firefox135 support

---

src/client/body.rs
src/client/decoder.rs
src/client/websocket/mod.rs
src/util/client/connect/dns.rs
src/util/client/connect/http.rs
src/util/client/pool.rs
src/util/service/oneshot.rs

This pull request focuses on replacing the `futures_util::ready!` macro with the `std::task::ready!` macro across multiple files to streamline the codebase. The changes span several modules, including `body.rs`, `decoder.rs`, `websocket/mod.rs`, `dns.rs`, `http.rs`, `pool.rs`, and `oneshot.rs`.
* [`src/client/body.rs`](diffhunk://#diff-7038768ab4f60be7f7e1ee48b88ee66eeaa34e614f87e52d2bb1647f214503e4L4-R4): Replaced `futures_util::ready!` with `std::task::ready!` in various functions and implementations. [[1]](diffhunk://#diff-7038768ab4f60be7f7e1ee48b88ee66eeaa34e614f87e52d2bb1647f214503e4L4-R4) [[2]](diffhunk://#diff-7038768ab4f60be7f7e1ee48b88ee66eeaa34e614f87e52d2bb1647f214503e4L271-R271) [[3]](diffhunk://#diff-7038768ab4f60be7f7e1ee48b88ee66eeaa34e614f87e52d2bb1647f214503e4L326-R326) …

refactor: reduce dependency on `futures-core` / `futures-util`

---

examples/connect_via_lower_priority_tokio_runtime.rs
src/client/websocket/mod.rs

This pull request introduces a new method to the `WebSocketRequestBuilder` in the `src/client/websocket/mod.rs` file to allow configuration of the websocket read buffer size.
* Added `read_buffer_size` method to set the websocket read buffer size in `WebSocketRequestBuilder`.

feat(websocket): Added `read_buffer_size` optional config

---

Cargo.toml

See https://github.com/sfackler/rust-openssl/pull/2360 and https://nvd.nist.gov/vuln/detail/CVE-2025-24898. From the rust-openssl PR:
> `SSL_select_next_proto` can return a pointer into either the client or server buffers, but the type signature of the function previously only bound the output buffer to the client buffer. This can result in a UAF in situations where the server slice does not point to a long-lived allocation.
Thanks to Matt Mastracci for reporting this issue.

build(deps): update boring requirement from 4.15.7 to 4.15.8

---

src/client/http.rs
tests/cookie.rs

This pull request introduces a new method to clear cookies from the client's `CookieStore` and includes corresponding tests. The most important changes are:
Enhancements to `ClientRef`:
* Added a new method `clear_cookies` to the `ClientRef` implementation, which clears all cookies from the client's `CookieStore`. This method requires the `cookies` feature to be enabled.
Code cleanup:
* Removed redundant checks for empty cookies in the `set_cookies` method of the `ClientRef` implementation. [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L1692-L1696) [[2]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L1717-R1732)
Testing:
* Added a new test `clear_cookies` in `tests/cookie.rs` to verify that the `clear_cookies` …

feat(client): Added a clear cookies function

---

src/client/http.rs

This pull request includes a deprecation notice for a method in the `Client` implementation in the `src/client/http.rs` file. The deprecated method is `set_cookies_by_ref`, and users are advised to use the `set_cookies` method with a collection of `HeaderValue` instead.
Deprecation notice:
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90R1525-R1528): Added a deprecation notice for the `set_cookies_by_ref` method, recommending the use of `set_cookies` with a collection of `HeaderValue` instead.

feat(client): deprecated `set_cookies_by_ref`

---

src/client/http.rs
src/redirect.rs

This pull request involves the removal of the `redirect_with_proxy_auth` feature from the HTTP client in the `src/client/http.rs` file. The changes simplify the codebase by removing associated configurations, methods, and references to this feature.
Key changes include:
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L107): Removed the `redirect_with_proxy_auth` field from the `Config` and `ClientInner` structs. [[1]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L107) [[2]](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L1638)
* [`src/client/http.rs`](diffhunk://#diff-5a9090205b95168aa13d30e00f2d23d2e5f2cb231e195f4a56b1775bd6118b90L610-L639): Deleted the …

feat(client): Remove cross-origin redirect proxy support

---

README.md
src/lib.rs

This pull request includes updates to the `README.md` file and the `src/lib.rs` file, focusing on dependency updates, feature enhancements, and documentation improvements.
* Updated `rquest` to version `3.0.1-rc3` and corrected the name of `rquest-util` in `README.md` (`[README.mdL31-R32](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L31-R32)`).
* Changed the emulation version from `Firefox133` to `Firefox135` in both `README.md` and `src/lib.rs` (`[[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L45-R45)`, `[[2]](diffhunk://#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L36-R36)`, `[[3]](diffhunk://#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L60-R60)`).
* Replaced …

docs: update docs

---

src/client/http.rs
src/cookie.rs

This pull request introduces several changes to the `Client` and `CookieStore` implementations in the `src/client/http.rs` and `src/cookie.rs` files. The changes primarily focus on adding new methods for cookie management and refactoring existing methods for improved functionality.
* Added a new method `insert_cookie` to the `Client` implementation to insert cookies into the `CookieStore` for a specified URL. This method is conditional on the `cookies` or `cookies-abstract` features being enabled.
* Refactored the `remove_cookie` method in the `Client` implementation to use the `remove` method instead of `remove_cookie` in the `CookieStore`.
* Introduced a new method `insert` in the `CookieStore` trait for inserting cookies into the store for a specified URL.
* Refactored the …

refactor(cookie): redesign cookie store API signature

---

src/client/websocket/message.rs

This pull request introduces a new method to the `Utf8Bytes` implementation in the `src/client/websocket/message.rs` file. The most significant change is the addition of a method that allows creating a `Utf8Bytes` object from a `Bytes` object without checking the encoding, with a clear safety warning.
Enhancements to `Utf8Bytes` implementation:
* [`src/client/websocket/message.rs`](diffhunk://#diff-62aff5075aa609ffcfa6f076853afd639350480e15c9953320c0f74ea6128c63R18-R27): Added the `from_bytes_unchecked` method to `impl Utf8Bytes` to create a `Utf8Bytes` object from a `Bytes` object without checking the encoding. This method includes a safety warning indicating that the bytes must be valid UTF-8.

feat(ws): impl `from_bytes_unchecked` of `Utf8Bytes`

---

src/client/http.rs
tests/badssl.rs

close: https://github.com/0x676e67/rquest/issues/555

feat(client): Add a straightforward method for SSL pinning setup

---

src/client/response.rs

docs(response): Clarify in docs that `Response::content_length()` is not based on the `Content-Length` header

---

Cargo.toml

fix: Cargo.lock v0.26.1
```bash
error[E0599]: no function or associated item named `from_bytes_unchecked` found for struct `Utf8Bytes` in the current scope
--> src/client/websocket/message.rs:25:38
|
25 | ...Utf8Bytes::from_bytes_unchecked(bytes) })
|               ^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Utf8Bytes`
|
= note: the full type name has been written to '/Users/gngpp/VSCode/rquest/target/debug/deps/rquest-3953d825e1554b74.long-type-8370843427114286319.txt'
= note: consider using `--verbose` to print the full type name to the console
note: if you're trying to build a new `tokio_tungstenite::tungstenite::Utf8Bytes`, consider using `tokio_tungstenite::tungstenite::Utf8Bytes::from_static` which returns `tokio_tungstenite::tungstenite::Utf8Bytes`
--> …
```

build(deps): pin `tokio-tungstenite` to version `0.26.2`

---

src/client/http.rs
src/util/client/request.rs
tests/client.rs
tests/client_update.rs

For cookies, if you want to keep the order, then you can only insert the cookies in order. There is no way to specify sorting for a value.

fix(client): Adapt sorting for duplicate headers such as cookies

---

src/client/http.rs
src/client/request.rs
tests/brotli.rs
tests/deflate.rs
tests/gzip.rs
tests/zstd.rs

This pull request includes changes to the `src/client/http.rs` and `src/client/request.rs` files to add support for allowing compression in HTTP requests. The most important changes include the introduction of a new `allow_compression` field in the `Request` struct, modifications to the `Client` implementation to handle compression headers, and the addition of helper functions to manage headers related to compression.
* [`src/client/request.rs`](diffhunk://#diff-aef10c34afeb6a03726464ce7663a34aa00b5a567bd732ca4847aa9d5a2d6c56R30): Introduced a new `allow_compression` field in the `Request` struct and added methods to get and set this field. This field is used to determine if the request should announce support for compression. [[1]](diffhunk://#diff-aef10c34afeb6a03726464ce7663a34aa00b5a56 …

feat(request): optionally allow compression in request

---

src/client/http.rs
src/tls/config.rs
src/tls/conn/boring.rs

Writes a SSLKEYLOGFILE that can be used in wireshark

feat(client): Adds support for SSLKEYLOGFILE output from client

---

examples/emulation_firefox.rs
examples/emulation_twitter.rs
src/tls/config.rs
src/tls/conn/boring.rs
tests/badssl.rs

the boringssl `set_curves_list()` has been the much more stable API overtime. With previous builds of boringSSL we've had to deal with naming changes that cause set_curves() API to not compile.

feat(tls): add API to set list of stable curves

---

src/core/client/connect/dns.rs
src/core/client/connect/proxy/mod.rs

This reverts commit e913768cf1be11b277b9b84b2f31b0090e426450.
from: https://github.com/hyperium/hyper/issues/3900

Revert "fix(dns): prefer IPv6 addresses before IPv4 even if resolver ordered differently (#658)"

---

Cargo.toml
src/client/body.rs
src/client/client/future.rs
src/client/client/mod.rs
src/client/client/service.rs
src/client/middleware/mod.rs
src/client/middleware/retry/mod.rs

close: https://github.com/0x676e67/wreq/issues/706

refactor(client): Move HTTP/2 safe retry logic into `tower` middleware

---

Cargo.toml
src/error.rs

fix(deps): upgrade url to v2.5.4 (CVE-2024-12224)
Addresses security vulnerability in URL parsing
Ref: GHSA-h97m-ww89-6jmq

fix(deps): upgrade url to v2.5.4 to address CVE-2024-12224

---

src/client/http/mod.rs

This was a legacy option for disabling the connection pool, which could be confusing. The connection pool can still be disabled by setting pool_max_idle_per_host to 0.

refactor(client): remove `no_keepalive` method

---

Cargo.toml
src/client/multipart.rs
src/lib.rs

close: https://github.com/0x676e67/wreq/issues/901

build(deps): minimize out-of-the-box dependencies

---

src/core/client/connect/http.rs

from: https://docs.rs/tokio/latest/tokio/net/struct.TcpSocket.html#method.from_std_stream

refactor(connect): safely convert `socket2::Socket` to Tokio `TcpSocket`
